sudo: required
language: node_js
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "8"
  - "7"
  - "6"
before_install:
  - docker build -t sebi55/whatkindofdeveloperareyou .
script:
  - 'npm run cover'
  - 'npm run check-coverage'
  - 'npm run build'
after_success:
  - 'npm run report-coverage'
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sebi55/whatkindofdeveloperareyou;
    fi