sudo: required
language: node_js
services:
  - docker
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "8"
  - "7"
  - "6"
before_install:
  - docker build .
script:
  - 'npm run cover'
  - 'npm run check-coverage'
  - 'npm run build'
after_success:
  - 'npm run report-coverage'